# Build & publish
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Functions use esbuild bundler (good defaults)
[functions]
  node_bundler = "esbuild"

# API routes (specific first)
# Chat summary (kept for later production use)
[[redirects]]
  from = "/api/summarize"
  to = "/.netlify/functions/summarize"
  status = 200

# Dictionary proxy (server-side lookup to avoid Safari/CORS issues)
[[redirects]]
  from = "/api/define"
  to = "/.netlify/functions/define"
  status = 200

# SPA fallback (last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
