# --- Netlify config for PGWAIReader ---

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Route every /api/* request to the corresponding Netlify Function
# /api/define      -> /.netlify/functions/define
# /api/summarize   -> /.netlify/functions/summarize
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

# (Optional but recommended) SPA fallback for client-side routing
# If your site is a single-page app, keep this. If not, you can remove it.
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
