# ------------------------------
# Build configuration
# ------------------------------
[build]
  command = "npm run build"
  publish = "dist"

# ------------------------------
# Netlify Functions
# ------------------------------
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# ------------------------------
# Redirects
# ------------------------------

# API route for ChatGPT summaries
[[redirects]]
  from = "/api/summarize"
  to = "/.netlify/functions/summarize"
  status = 200

# Catch-all redirect for React SPA (must stay last!)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

