# --- Netlify config for PGWAIReader ---

# Build (explicit; works great with Vite)
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Ensure the words list is bundled with functions (in addition to per-function config).
  included_files = [
    "public/content/games/wordweb/words.txt"
  ]

# -----------------------------
# API routes -> Netlify Functions
# Examples:
#   /api/define       -> /.netlify/functions/define
#   /api/summarize    -> /.netlify/functions/summarize
#   /api/fetchBook    -> /.netlify/functions/fetchBook
#   /api/searchIndex  -> /.netlify/functions/searchIndex
# -----------------------------
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

# -----------------------------
# SPA fallback (client-side routing)
# Keep LAST so it doesn't swallow the /api/* redirect
# -----------------------------
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# -----------------------------
# Caching headers
# -----------------------------

# Covers list for the library page; safe to cache for a day and immutable until next deploy/script run.
[[headers]]
  for = "/content/library.json"
  [headers.values]
    Cache-Control = "public, max-age=86400, immutable"

# Make sure Word Web assets (if you ever serve static JSON there) are always fresh.
[[headers]]
  for = "/content/games/wordweb/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Quiz bank: ensure the browser fetches the latest daily.
[[headers]]
  for = "/content/games/quiz/questions.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Optional: basic security headers for all static assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"

# -----------------------------
# Local dev (optional but handy)
# -----------------------------
[dev]
  framework = "vite"   # change/remove if not using Vite
  command = "npm run dev"
  targetPort = 5173    # Vite default
  port = 8888          # Netlify Dev proxy port
  autoLaunch = false
